---
#
# Author: Aniruddha Gokhale
# CS4287/5287 Principles of Cloud Computing
# Created: Fall 2024
#
# Purpose: 
#   This playbook can be used if you would like to try doing
#   the actions from the master playbook step by step. Simply
#   copy the next play from the master to here and execute
#   just this play and make sure it is working. If everything
#   works correctly, you may then terminate your VMs once again
#   and just run the master playbook end to end
#

################################################################
### Play 1: check if required variables are defined or not.
#           If not defined then simply exit the entire play
#
################################################################

- name: "Check if required variables that drive the deployment are defined"
  hosts: CloudVMs # this alias is specified in the inventory file
  remote_user:  "cc"  # since the play executes on LocalMC,
                                    # we use the local user
  gather_facts: no
  collections:    # collections is like import the necessary Ansible
                  # galaxy packages needed for the play to execute
  - ansible-base

  tasks:
  # @@ You have to write the following child playbook @@
   - name: Ping my hosts
     ansible.builtin.ping:
  #- import_tasks: tasks/playbook_check_variables.yaml
   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

#####################################################
### Play 2: Create VMs on the Cloud
#
#####################################################
- name: launch a compute instance
  hosts: localhost
  vars_files:
   - variables.yaml
  tasks:
    - name: launch an instance
      openstack.cloud.server:
        cloud: CH-822922 
        state: present
        name: "{{ item }}"
        #availability_zone: az2
        image: cdbbbe8f-f5a5-499c-b4b3-9b7dbecbdfd5
        network: CH-822922-net
       # key_name: 
        timeout: 200
        flavor: m1.medium
        security_groups:
        - default
        - ENABLE_SSH
        auto_ip: false
      loop: "{{ server_names }}"
#####################################################

#####################################################
### Play 3: Get facts from Cloud VM
#
# In this play, you must retrieve various facts of the
# VMs you have created. The most important are their
# private IP addresses that you will need in subsequent
# plays
#####################################################
- name: "Play 3: Perform fact gathering on all Cloud VMs"
  hosts: LocalMC  # specified in the Inventory file
  #vars:
    #local_user: amarn
  vars_files:
   - variables.yaml
  remote_user:  "{{ local_user }}"
  gather_facts: no
  become: false
  collections:
  - ansible-base
  - openstack.cloud.collection

  tasks:    # the task to be performed
  # @@ You have to write the following child playbook @@
  #- import_tasks: tasks/playbook_retrieve_facts_vms.yaml
  - name: Keeping up with the Kardashians
    openstack.cloud.server_info:
      cloud: CH-822922
      name: "*_kardashian"
      filters:
        vm_state: active
    register: our_servers

  - name: Display output of our_servers
    ansible.builtin.debug:
      msg : "{{ our_servers['servers'] }}"

  - name: Write the facts in Inventory
    lineinfile:
     path: Inventory.ini
     insertafter: "^[CloudVMs]$"
     line: "{{ item['name'] }}={{ item['addresses']['CH-822922-net'][0]['addr'] }}"
    loop: "{{ our_servers['servers'] }}"

#####################################################
